parameters: { }

services:
  _defaults:
    autowire: true        # automatyczne wstrzykiwanie zależności
    autoconfigure: true   # automatyczne tagowanie standardowych usług
    bind: { }

  # Rejestruj wszystkie klasy jako serwisy (poza wyjątkami niżej)
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Kontrolery – wymagany tag, żeby działało wstrzykiwanie argumentów do akcji
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
