version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coach_support_db
    environment:
      POSTGRES_DB: coach_support_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coach123
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - coach_support_net

  backend:
    build:
      context: ./backend
    container_name: coach_support_backend
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: "postgresql://postgres:coach123@db:5432/coach_support_db?serverVersion=16&charset=utf8"
    networks:
      - coach_support_net
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
    container_name: coach_support_frontend
    ports:
      - "3000:80"
    networks:
      - coach_support_net
    depends_on:
      - backend

networks:
  coach_support_net:
    driver: bridge